[versions]
agp = "8.9.0"
agp-tooling = "8.9.0"
gradle-tooling = "8.9"
# gradle-tooling = "v1.0-t2"

junit-jupiter = "5.10.2"
kotlin = "2.1.0"
kotlin-coroutines = "1.10.2"
tree-sitter = "1.0.1"
editor = "0.23.7"
glide = "5.0.4"
androidx-vectordrawable = "1.2.0"
androidx-navigation = "2.7.7"
ksp = "2.1.0-1.0.28"
antlr4 = "4.13.2"
androidx-work = "2.9.0"
androidx-espresso = "3.5.1"
retrofit = "3.0.0"
markwon = "4.6.2"
logback = "1.5.3"
realm = "10.18.0"
benchmark = "1.2.4"
benchmark-junit4 = "1.2.4"
okhttp = "4.12.0"
gson = "2.10.1"

[libraries]
# Kotlin compiler embeddable for Kotlin LSP
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-scripting-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable", version.ref = "kotlin" }

# Dependencies in composite build
composite-appintro = { module = "com.itsaky.tom.rv2ide.build:appintro" }
composite-desugaringCore = { module = "com.itsaky.tom.rv2ide.build:desugaring-core" }
composite-fuzzysearch = { module = "com.itsaky.tom.rv2ide.build:fuzzysearch" }
composite-googleJavaFormat = { module = "com.itsaky.tom.rv2ide.build:google-java-format" }
composite-javaCompiler = { module = "com.itsaky.tom.rv2ide.build:java-compiler" }
composite-javac = { module = "com.itsaky.tom.rv2ide.build:javac" }
composite-jdkCompiler = { module = "com.itsaky.tom.rv2ide.build:jdk-compiler" }
composite-jdkJdeps = { module = "com.itsaky.tom.rv2ide.build:jdk-jdeps" }
composite-javapoet = { module = "com.itsaky.tom.rv2ide.build:javapoet" }
composite-jaxp = { module = "com.itsaky.tom.rv2ide.build:jaxp" }
composite-jdt = { module = "com.itsaky.tom.rv2ide.build:jdt" }
composite-layoutlibApi = { module = "com.itsaky.tom.rv2ide.build:layoutlib-api" }

# AndroidIDE
androidide-ts = { module = "io.github.mohammed-baqer-null:android-tree-sitter", version.ref = "tree-sitter" }
androidide-ts-java = { module = "io.github.mohammed-baqer-null:tree-sitter-java", version.ref = "tree-sitter" }
androidide-ts-json = { module = "io.github.mohammed-baqer-null:tree-sitter-json", version.ref = "tree-sitter" }
androidide-ts-kotlin = { module = "io.github.mohammed-baqer-null:tree-sitter-kotlin", version.ref = "tree-sitter" }
androidide-ts-cpp = { module = "io.github.mohammed-baqer-null:tree-sitter-cpp", version.ref = "tree-sitter" }
androidide-ts-log = { module = "io.github.mohammed-baqer-null:tree-sitter-log", version.ref = "tree-sitter" }
androidide-ts-xml = { module = "io.github.mohammed-baqer-null:tree-sitter-xml", version.ref = "tree-sitter" }

# Common
common-editor = { module = "io.github.rosemoe:editor", version.ref = "editor" }
common-utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }
common-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
common-glide_ap = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
common-jsoup = { module = "org.jsoup:jsoup", version = "1.21.2" }
common-antlr4 = { module = "org.antlr:antlr4", version.ref = "antlr4" }
common-antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr4" }
common-javaparser = { module = "com.github.javaparser:javaparser-symbol-solver-core", version = "3.27.0" }
common-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.18.0" }
common-io = { module = "commons-io:commons-io", version = "2.20.0" }
common-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
common-kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
common-kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
common-jkotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
common-eventbus_ap = { module = "org.greenrobot:eventbus-annotation-processor", version = "3.3.1" }
common-javapoet = { module = "com.squareup:javapoet", version = "1.13.0" }
common-ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
common-jsonrpc = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version = "0.24.0" }
common-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.13" }
common-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
common-retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
common-markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
common-markwon-extStrikethrough = { module = "io.noties.markwon:ext-strikethrough", version.ref = "markwon" }
common-markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }
common-markwon-recycler = { module = "io.noties.markwon:recycler", version.ref = "markwon" }
common-hiddenApiBypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version = "6.1" }
common-termuxAmLib = { module = "com.termux:termux-am-library", version = "v2.0.0" }
common-charts = { module = "com.github.AppDevNext:AndroidChart", version = "3.1.0.21" }
common-datastore = { module = "androidx.datastore:datastore-preferences", version = "1.1.7" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# AndroidX
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.7.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
androidx-collection = { module = "androidx.collection:collection", version = "1.4.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version = "1.2.0" }
androidx-drawer = { module = "androidx.drawerlayout:drawerlayout", version = "1.2.0" }
androidx-grid = { module = "androidx.gridlayout:gridlayout", version = "1.0.0" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
androidx-vectors = { module = "androidx.vectordrawable:vectordrawable", version.ref = "androidx-vectordrawable" }
androidx-animated_vectors = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "androidx-vectordrawable" }
androidx-core = { module = "androidx.core:core", version = "1.13.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-fragment_ktx = { module = "androidx.fragment:fragment-ktx", version = "1.6.2" }
androidx-libDesugaring = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.4" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
androidx-transition = { module = "androidx.transition:transition-ktx", version = "1.5.0" }
androidx-nav-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-nav-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-tracing = { module = "androidx.tracing:tracing", version = "1.2.0" }
androidx-tracing-ktx = { module = "androidx.tracing:tracing-ktx", version = "1.2.0" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version = "1.0.0" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version = "1.0.0" }
#noinspection GradleDependency
androidx-window-v1alpha9 = { module = "androidx.window:window", version = "1.0.0-alpha09" }
androidx-work = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-work-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

# Google
google-material = { module = "com.google.android.material:material", version = "1.13.0" }
google-gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
google-guava = { module = "com.google.guava:guava", version = "32.1.3-android" }
google-auto-value-annotations = { module = "com.google.auto.value:auto-value-annotations", version = "1.10.4" }
google-auto-value-ap = { module = "com.google.auto.value:auto-value", version = "1.10.4" }
google-auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.1.1" }
google-auto-service = { module = "com.google.auto.service:auto-service", version = "1.1.1" }
google-protobuf = { module = "com.google.protobuf:protobuf-javalite", version = "3.25.3" }
google-java-format = { module = "com.google.googlejavaformat:google-java-format", version = "1.20.0" }
google-flexbox = { module = "com.google.android.flexbox:flexbox", version = "3.0.0" }

# Bytecode utilities
asm = { module = "org.ow2.asm:asm", version = "9.7.1" }

# AAPT2
aapt2-common = { module = "com.android.tools:common", version = "31.4.1" }
aapt2-annotations = { module = "com.android.tools:annotations", version = "31.2.2" }
aapt2-jb-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
aapt2-proto = { module = "com.android.tools.build:aapt2-proto", version = "8.3.0-10880808" }

# use logback-core from logback-android instead
#logging-logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logging-logback-core = { module = "com.itsaky.tom.rv2ide.build:logback-core" }
logging-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# XML
xml-xercesImpl = { module = "xerces:xercesImpl", version = "2.12.2" }
xml-apis = { module = "xml-apis:xml-apis", version = "2.0.2" }
xml-remark = { module = "com.kotcrab.remark:remark", version = "1.2.0" }
xml-resolver = { module = "xml-resolver:xml-resolver", version = "1.2" }
xml-jb-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }

# GIT
git-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version = "6.8.0.202311291450-r" }

# Tests
tests-junit = { module = "junit:junit", version = "4.13.2" }
tests-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
tests-junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
tests-google-truth = { module = "com.google.truth:truth", version = "1.4.4" }
tests-robolectric = { module = "org.robolectric:robolectric", version = "4.11.1" }
tests-androidx-test-core = { module = "androidx.test:core", version = "1.5.0" }
tests-androidx-test-runner = { module = "androidx.test:runner", version = "1.5.2" }
tests-androidx-test-rules = { module = "androidx.test:rules", version = "1.5.0" }
tests-androidx-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
tests-androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidx-work" }
tests-androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
tests-androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-espresso" }
tests-androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version = "2.3.0" }
tests-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "5.2.1" }
tests-mockk = { module = "io.mockk:mockk", version = "1.13.10" }
tests-barista = { module = "com.adevinta.android:barista", version = "4.3.0" }

# Tooling
tooling-builderModel = { module = "com.android.tools.build:builder-model", version.ref = "agp-tooling" }
tooling-gradleApi = { module = "com.github.AndroidIDE-Rv2Official:tom-gradle-tooling-api", version.ref = "gradle-tooling" }

tooling-slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.12" }

# Kotlin Language Server dependencies
org-eclipse-lsp4j-lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version = "0.24.0" }
org-eclipse-lsp4j-jsonrpc = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version = "0.24.0" }
com-jetbrains-intellij-java-decompiler = { module = "com.jetbrains.intellij.java:java-decompiler-engine", version = "232.10227.8" }
org-jetbrains-exposed-core = { module = "org.jetbrains.exposed:exposed-core", version = "0.37.3" }
org-jetbrains-exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version = "0.37.3" }
org-jetbrains-exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version = "0.37.3" }
com-h2database-h2 = { module = "com.h2database:h2", version = "2.2.224" }
com-github-fwcd-ktfmt = { module = "com.facebook:ktfmt", version = "0.58" }
com-beust-jcommander = { module = "com.beust:jcommander", version = "1.82" }
org-xerial-sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version = "3.45.0.0" }
hamcrest-all = { module = "org.hamcrest:hamcrest-all", version = "1.3" }
junit-junit = { module = "junit:junit", version = "4.13.2" }
org-openjdk-jmh-core = { module = "org.openjdk.jmh:jmh-core", version = "1.37" }
org-openjdk-jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version = "1.37" }
org-jetbrains-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
org-jetbrains-kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
org-jetbrains-kotlin-ktscompiler = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler", version.ref = "kotlin" }
org-jetbrains-kotlin-kts-jvm-host-unshaded = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host-unshaded", version.ref = "kotlin" }
org-jetbrains-kotlin-sam-with-receiver-compiler-plugin = { module = "org.jetbrains.kotlin:sam-with-receiver-compiler-plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-scripting-jvm-host = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host", version.ref = "kotlin" }
com-google-guava-guava = { module = "com.google.guava:guava", version = "32.1.3-jre" }

# Classpaths
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
nav-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidx-navigation" }
androidx-benchmark-junit4 = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "benchmark-junit4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.6" }
com-github-jk1-tcdeps = { id = "com.github.jk1.tcdeps", version = "1.6.2" }
com-jaredsburrows-license = { id = "com.jaredsburrows.license", version = "0.9.8" }
io-gitlab-arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.22.0" }
